run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

linters-settings:
  govet:
    enable-all: true

issues:
  exclude-use-default: false
