package graph

import "github.com/zatrano/zatrano/pkg/core"

// This file will not be regenerated by gqlgen.

// Resolver is the root type passed to generated executable schema.
type Resolver struct {
	App *core.App
}
